# Generated by Django 3.1.7 on 2021-04-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Textarea', models.CharField(default='', max_length=700)),
                ('Blog_id', models.IntegerField(default=0)),
            ],
        ),
    ]
